### ISSUE TITLE
1 consistently repeatable issue...

### ISSUE THREAD

**Issue by FraugDib** [m4yc3x/godotbuddy#1]
... is that this thing is too friggin' AWESOME!

Seriously, I use Groq/llama70b as my daily driver, but your godotbuddy seems to produce way better results. Not sure if that's something you did or if it just operates better inside of GODOT (I guess it is a lot less variables to operate in than IRL)?

**Comment by m4yc3x** [comment]
Thanks man! I'm glad you're enjoying the plugin. 

The inference works much better due to the [prompt engineering](https://github.com/m4yc3x/godotbuddy/blob/c9339b21faea6c80b85229f2c190404650c7810b/addons/godotbuddy/godotbuddy.gd#L11) before your requests are sent.
